export default {
  "": "",
  appname: "Velostics",
  "header.totaltrips": "Total Trips",
  "header.totalmiles": "Total Miles",
  "header.totalearnings": "Total Earnings",
  "navigation.shipments": "Shipments",
  "navigation.requested": "Requested",
  "navigation.scheduled": "Scheduled",
  "navigation.profile": "Profile",
  "navigation.messages": "Messages",
  "navigation.notifications": "Notifications",
  "auth.login": "LOGIN",
  "auth.signup": "SIGN UP",
  "signin.login": "Login",
  "signin.welcomemessage": "Welcome to Velostics",
  "signin.enterphone": "Enter your mobile phone number",
  "signin.verficationmessage":
    "We will send a verification code to the phone number below.",
  "signin.placeholder.phone": "PHONE NUMBER",
  "signin.privacypolicy": "Privacy Policy",
  "signin.privacypolicytext": "By continuing you agree to our ",
  "signin.placeholder.password": "PASSWORD",
  "signin.forgotpassword": "Forgot Password?",
  "signin.buttontext": "CONTINUE",
  "signin.signupmessage": "Don't have an account?",
  "signin.signupbuttontext": "Sign Up",
  "signin.or": "OR",
  "signin.otp.button": "Verify",
  "signin.otp.title": "Enter verification code",
  "signin.otp.resend": "Resend",
  "signup.header": "Sign Up",
  "signup.username": "USERNAME",
  "signup.password": "PASSWORD",
  "signup.confirmpassword": "CONFIRM PASSWORD",
  "signup.buttonText": "NEXT",
  "signup.buttondone": "DONE",
  "signin.otp.placeholder": "Verification code",

  "signup.buttoncreate": "CREATE",
  "signup.hittheroad": "Let's Hit the Road!",
  "signup.firstname": "FIRST/GIVEN NAME",
  "signup.lastname": "LAST/FAMILY NAME",
  "signup.phonenumber": "PHONE NUMBER",
  "signup.confirmpassword": "CONFIRM PASSWORD",
  "signup.emailaddress": "EMAIL ADDRESS",
  "signup.state": "STATE",
  "signup.vehiclephotos": "VEHICLE PHOTOS",
  "signup.licensenumber": "DRIVER'S LICENSE",
  "signup.platenumber": "LICENSE PLATE NUMBER",
  "signup.vehiclename": "VEHICLE NAME",
  "signup.vehiclemodel": "VEHICLE MODEL",
  "signup.profilephotoheading": "Profile Photo",
  "signup.profilephotomessage": "Capture a photo of yourself",
  "signup.truckphotoheading": "Vehicle Photos",
  "signup.truckphotomessage1": "Capture photos of different",
  "signup.truckphotomessage2": "angles of your truck",
  "signup.profilepicloading": "Uploading...",
  "otpscreen.title": "Confirm your identity",
  "otpscreen.des": "Enter the code sent to your phone number ending with",
  "otpscreen.sendotp": "Send code again",
  "otpscreen.sending": "Sending...",
  "imagebrowser.exit": "Exit",
  "imagebrowser.choose": "Choose",
  "signup.carrier": "CARRIER",
  "navbar.back": "Back",
  "requestedlist.title": "Requested Trips",
  "requestitem.seedetails": "See Details",
  "upcomingtrips.title": "Upcoming Trips",
  "upcomingtrips.buttontext": "LEAVE FOR PICKUP",
  "requestedscreen.title": "Requested Trips",
  "scheduledscreen.title": "Scheduled Trips",
  "profilescreen.title": "Profile",
  "profilescreen.driverinfoheader": "About me",
  "profilescreen.drivername": "First name",
  "profilescreen.driverlastname": "Last name",
  "profilescreen.driverlicense": "License",
  "profilescreen.phoneno": "Phone",
  "profilescreen.email": "Email",
  "profilescreen.truckphotoheading": "Truck Photos",
  "profilescreen.truckowner": "Truck Owner",
  "profilescreen.truckinfoheader": "My Truck",
  "profilescreen.licenseplate": "License Plate",
  "profilescreen.truckmodel": "Truck Model",
  "profilescreen.truckmake": "Truck Make",
  "profilescreen.capacity": "Capacity",
  "profilescreen.pictures": "Pictures",
  "profilescreen.truckuploadheading":
    "Tap the camera icon to capture photos your truck",
  "profilescreen.logout": "Logout",
  "profilescreen.carrierheader": "My Carrier",
  "profilescreen.carrier": "Carrier",
  "profilescreen.contact": "Contact",
  "profilescreen.phonenumber": "Phone",
  "profilescreen.carrieremail": "Email",
  "profilescreen.logininfoheader": "My Login",
  "profilescreen.username": "Username",
  "profilescreen.password": "Password",
  "profilescreen.seeall": "See All",
  "editprofile.title": "Edit Profile",
  "editprofile.save": "Save",
  "editprofile.cancel": "Cancel",
  "profilescreen.edit": "Edit",
  "requestedtrip.title": "Requested Trip",

  "status.requested": "REQUESTED",
  "status.scheduled": "SCHEDULED",
  "status.unassigned": "UNASSIGNED",
  "status.enroute": "EN ROUTE",
  "status.ontime": "ON TIME",
  "status.delayed": "DELAYED",
  "status.approaching": "APPROACHING",
  "status.loading": "LOADING",
  "status.arrived": "ARRIVED",
  "status.cancelled": "CANCELLED",
  "status.created": "CREATED",
  "status.on_schedule": "ON SCHEDULE",
  "status.processing": "PROCESSING",
  "status.enroutetopickup": "EN ROUTE TO PICKUP",
  "status.enroutetodestination": "EN ROUTE TO DESTINATION",
  "status.unloading": "UNLOADING",
  "status.completed": "COMPLETED",
  "trip.pickup": "Pickup",
  "trip.complete": "COMPLETE TRIP",
  "trip.completed": "COMPLETED TRIP",
  "trip.closetrip": "CLOSE TRIP",
  "trip.startunloading": "START UNLOADING",
  "trip.beginchecklist": "BEGIN CHECKLIST",
  "trip.delivery": "Delivery",
  "trip.reportarrival": "REPORT ARRIVAL",
  "trip.leavefordes": "LEAVE FOR DESTINATION",
  "trip.estimateddistance": "Estimated Distance",
  "trip.accept": "ACCEPT",
  "trip.starttrip": "LEAVE FOR PICKUP",
  "trip.loadtruck": "BEGIN CHECKLIST",
  "trip.reject": "REJECT & EXPLAIN",
  "trip.startloading": "START LOADING",
  "trip.reportdelay": "REPORT DELAY",
  "trip.leaveforpickup": "LEAVE FOR PICKUP",
  "trip.startprocessing": "START LOADING",
  "trip.manifest": "MANIFEST",
  "trip.notes": "INSTRUCTIONS",
  "trip.qrcode": "View QR Code",
  "trip.photos": "PHOTOS",
  "trip.team": "Team",
  "trip.docs": "DOCUMENTS",
  "trip.docs.bol": "BILL OF LOADING",
  "trip.docs.receipts": "RECEIPTS",
  "trip.docs.others": "OTHERS",
  "trip.docs.pod": "PROOF OF DELIVERY",
  "trip.photos.manifest": "MANIFEST IMAGES",
  "trip.photos.truck": "TRUCK IMAGES",
  "trip.photos.others": "OTHERS",
  "trip.upcomingtrip": "Upcoming Trip",
  "trip.collaborators": "COLLABORATORS",
  "trip.docsuploadmessage":
    "Tap the camera icon to capture photos of important documents",
  "trip.title.completed": "Completed Trip",
  "trip.title.requested": "Requested Trip",
  "trip.title.scheduled": "Scheduled Trip",
  "trip.title.currenttrip": "Current Trip",
  "trip.title.loading": "Loading...",
  "trip.title.error": "Trip Detail",
  "manifest.liquidsolid": "Liquid/Solid: ",
  "manifest.poundstogallons": "Pounds to Gallons: ",
  "manifest.packageno": "Package No: ",
  "manifest.plannedamount": "Planned Amount: ",
  "manifest.loadedpounds": "Loaded Pounds: ",
  "manifest.unloadedpounds": "Unloaded Pounds: ",
  "manifest.loadedgallons": "Loaded Gallons: ",
  "manifest.unloadedgallons": "Unloaded Gallons: ",
  "manifest.description": "Description: ",
  "manifest.quantity": "Quantity: ",
  "manifest.length": "Length: ",
  "manifest.width": "Width: ",
  "manifest.height": "Height: ",
  "manifest.weight": "Weight: ",
  "processshipment.title": "Process Shipment",
  "processshipment.pre_loading.title":
    "You have completed loading. Leave for destination?",
  "processshipment.post_loading.title":
    "You are done unloading. Complete and close shipment?",
  "processshipment.yes": "Yes",
  "processshipment.no": "No",
  "process.finished": "FINISHED",
  "stage.driver": "Stage 1: Driver",
  "stage.qualifications": "Stage 2: Qualifications",
  "stage.loading": "Stage 3: Loading",
  "qrcode.title": "QR Code",
  "qr.message":
    "Please show this code to ground crew upon Arrival at the destination",
  "qr.button": "DONE",
  "rejection.title": "Requested Trip",
  "rejection.delaytitle": " ",
  "rejection.delay": "Current Trip",
  "rejection.reportdelay": "REPORT DELAY",
  "rejection.thanks": "Thank you!",
  "rejection.message": "Please indicate the reason for rejecting",
  "rejection.delaymessage": "Please indicate the reason for the delay",
  "rejection.button": "DONE",
  "rejection.placeholder": "Type here...",
  "tabs.current": "Current",
  "tabs.scheduled": "Scheduled",
  "tabs.requested": "Requested",
  "tabs.completed": "Completed",
  "tabs.shipments": "Shipments",
  "messages.title": "Notifications",
  "messages.header.new": "NEW",
  "messages.header.earlier": "EARLIER",
  "chat.viewcontacts": "View Team",
  "notification.driver": "Driver: ",
  "chat.goto": "Go To",
  "chatcontacts.title": "Contacts",
  "chatrole.lm": "Logistics Manager",
  "trip.contacts": "Messages",
  "trip.showmorephotos": "Show More Photos",
  "error.required": "Required Field",
  "error.valid.email": "Not a valid email",
  "error.validnumber": "Must be a valid number",
  "error.mustbephone": "Must be valid phone",
  "error.phone.required": "Phone is required",
  "error.username.required": "Phone is required",
  "error.password.minlength": "Min 6 characters",
  "error.password.required": "Password is required",
  "error.notripsavailable": "No Trips available",
  "error.signin.otp.minlength": "Should be  6 characters",
  "error.signin.otp.requried": "Verification code is required",
  "error.nonotification": "No Notifications for now.",
  "error.signup.firstname": "Not a valid name",

  "error.signup.driver.licence": "Not a valid Licence, Example (US 29292)",
  "error.signup.truck.licence": "Not a valid license plate format (US 233)",
  "error.signup.driver.licence.length": "Too big, try a shorter one.",
  "error.signup.email": "Not a valid email",
  "error.signup.email.required": "Email is required",
  "error.retry": "RETRY",
  "error.rejection.empty": "Please choose a reason",
  "contacts.owner": "Owner",
  "contacts.driver": "Driver",
  "contacts.follower": "Follower",
  "contacts.carrier-contact": "Carrier",
  "contacts.consignee-contact": "Consignee",
  "contacts.consignee-ground": "Consignee",
  "contacts.shipper-contact": "Shipper",
  "contacts.logisticsmanager": "Logistics Manager",
  "contacts.shipper-ground": "Shipper",
  "imagepicker.title": "Choose Image from",
  "imagepicker.gallery": "Gallery",
  "imagepicker.camera": "Camera",
  "imagepicker.loading": "Please wait...",
  "modal.warning.title": "Are you sure?",
  "modal.warning.confirm": "CONFIRM",
  "modal.warning.cancel": "CANCEL",
  "profile.edit.save": "SAVE",
  "profile.edit.cancel": "CANCEL",
  "error.profileupdate.name.required": "Required Field",
  "error.profileupdate.name.max": "Oops, name is too large.",
  // New
  "profilescreen.swtichLang": "Cambiar idioma a español",
  "profilescreen.changelanguage": "Language selection",
  "profilescreen.lastupdated": "Last updated",
  "profilescreen.lang.en": "English",
  "profilescreen.lang.es": "Español",
  "codepush.title": "An update is available!",
  "codepush.optionalupdatemessage":
    "An update is available. Would you like to install it?",
  "codepush.mandatoryupdatemessage":
    "An update is available that must be installed.",
  "codepush.installbuttonlabel": "Install",
  "codepush.optionalignorebuttonlabel": "Ignore",
  "codepush.mandatorycontinuebutton": "Continue",
  "notification.permission.title": "Notifications",
  "notification.permission.description":
    "We need your permission to send you notifications to ensure you never miss a shipment request.",
  "notification.button": "SET NOTIFICATION SETTINGS",
  "notification.permission.message": "You have a shipment request!",
  "location.permission.title": "Location",
  "location.permission.description":
    "Keep your shipment statuses accurate automatically and save time by always allowing location tracking.",
  "location.button": "SET LOCATION SETTINGS",
  "location.permission.message": "Shipment is approaching destination!",
  "shipments.section.requested": "Requested",
  "shipments.section.scheduled": "Scheduled",
  "shipments.section.completed": "Completed",
  "shipments.section.current": "Current",
  "trip.actionsheet.openmap": "Open in Maps",
  "trip.actionsheet.copyaddress": "Copy Address",
  "trip.actionsheet.cancel": "Cancel",
  "trip.actionsheet.checklist": "Begin Checklist",
  "checklist.complete.title": "Complete shipment checklist below",
  "trip.checklist.loading.heading": "Pickup Checklist",
  "trip.checklist.unloading.heading": "Destination Checklist",
  "trip.modal.completed.message":
    'You have completed all steps for this shipment \'s successful delivery. Would you like to mark this shipment as "Completed" and alert the Shipment Team?',
  "trip.modal.completed.title": "Shipment Complete?",
  "trip.modal.completed.button": "COMPLETE SHIPMENT",
  "trip.modal.enroute_to_destination.message":
    'You have completed all steps for this shipment\'s successful pickup. Would you like to mark this shipment as "EN Route to Destination" and alert the Shipment Team?',
  "trip.modal.enroute_to_destination.title": "EN ROUTE TO DESTINATION?",
  "trip.modal.enroute_to_destination.button": "UPDATE SHIPMENT",
  "imageupload.uploading": "Uploading..."
};
