export default {
  "header.totaltrips": "Total de Viajes",
  "header.totalmiles": "Millas Recorridas",
  "header.totalearnings": "Total de Ganancias",
  "navigation.shipments": "Envios",
  "navigation.requested": "Solicitado",
  "navigation.scheduled": "Coordinado",
  "navigation.profile": "Perfil",
  "navigation.messages": "Mensajes",
  "navigation.notifications": "Notificaciones",
  "auth.login": "INICIAR SESIÓN",
  "auth.signup": "REGISTRARSE",
  "signin.login": "Iniciar Sesion",
  "signin.welcomemessage": "Bienvenidos a Velostics",
  "signin.enterphone": "Introduzca su numeros telefonico",
  "signin.verficationmessage":
    "Enviaremos un código de verificación al número de teléfono a continuación.",
  "signin.placeholder.phone": "NUMERO TELEFONICO",
  "signin.privacypolicy": "Politica de Privacidad",
  "signin.privacypolicytext": "Al continuar, usted acepta nuestro",
  "signin.placeholder.password": "CONTRASEÑA",
  "signin.forgotpassword": "Ha olvidado su contraseña?",
  "signin.buttontext": "CONTINUAR",
  "signin.signupmessage": "No tiene una cuenta?",
  "signin.signupbuttontext": "Registrase",
  "signin.or": "O",
  "signin.otp.button": "Verificacion",
  "signin.otp.title": "Ingrese el codigo de verificacion",
  "signin.otp.resend": "Reenviar",
  "signup.header": "Registrase",
  "signup.username": "NOMBRE DE USUARIO",
  "signup.password": "CONTRASEÑA",
  "signup.confirmpassword": "CONFIRME SU CONTRASEÑA",
  "signup.buttonText": "SIGUIENTE",
  "signup.buttondone": "LISTO",
  "signin.otp.placeholder": "Codigo de Verificacion",
  "signup.buttoncreate": "CREAR",
  "signup.hittheroad": "Vamos ala carretera!",
  "signup.firstname": "PRIMER NOMBRE",
  "signup.lastname": "APELLIDO",
  "signup.phonenumber": "NUMERO TELEFONICO",
  "signup.confirmpassword": "CONFIRME SU CONTRASEÑA",
  "signup.emailaddress": "CORREO ELECTRONICO",
  "signup.state": "ESTADO",
  "signup.vehiclephotos": "FOTOS DE EL VEHICULO",
  "signup.licensenumber": "LICENCIA DE CONDUCIR",
  "signup.platenumber": "NUMERO DE PLACA",
  "signup.vehiclename": "NOMBRE DE VEHICULO",
  "signup.vehiclemodel": "MODELO DE VEHICULO",
  "signup.profilephotoheading": "Foto de Perfil",
  "signup.profilephotomessage": "Tome una foto Suya",
  "signup.truckphotoheading": "Fotos de Vehiculo",
  "signup.truckphotomessage1": "Capture fotos de diferentes",
  "signup.truckphotomessage2": "angulos de su camion",
  "signup.profilepicloading": "Cargando...",
  "otpscreen.title": "Confirme su Identidad",
  "otpscreen.des":
    "Ingrese el código enviado a su número de teléfono que termina con",
  "otpscreen.sendotp": "Enviee codigo de nuevo",
  "otpscreen.sending": "Enviando...",
  "imagebrowser.exit": "Salida",
  "imagebrowser.choose": "Escoger",
  "signup.carrier": "LINEA FLETERA",
  "navbar.back": "Atrás",
  "requestedlist.title": "Viajes Solicitados",
  "requestitem.seedetails": "Ver Detalles",
  "upcomingtrips.title": "Proximos Viajes",
  "upcomingtrips.buttontext": "SALIR A CARGAR",
  "requestedscreen.title": "Viajes Solicitados",
  "scheduledscreen.title": "Viajes Coordinados",
  "profilescreen.title": "Perfil",
  "profilescreen.driverinfoheader": "Acerca de mi",
  "profilescreen.drivername": "Primer nombre",
  "profilescreen.driverlastname": "Apellido",
  "profilescreen.driverlicense": "Licencia",
  "profilescreen.phoneno": "Telefono",
  "profilescreen.email": "Correo electronico",
  "profilescreen.truckphotoheading": "Fotos de camión",
  "profilescreen.truckowner": "Dueño de camion",
  "profilescreen.truckinfoheader": "Mi camion",
  "profilescreen.licenseplate": "Placa",
  "profilescreen.truckmodel": "Modelo de camion",
  "profilescreen.truckmake": "Marca de Camion",
  "profilescreen.capacity": "Capacidad",
  "profilescreen.pictures": "Fotos",
  "profilescreen.truckuploadheading":
    "Toque el icono de la camara para tomar fotos de su camion",
  "profilescreen.logout": "Cerrar Sesion",
  "profilescreen.carrierheader": "Mi Portador",
  "profilescreen.carrier": "Portador",
  "profilescreen.contact": "Contacto",
  "profilescreen.phonenumber": "Telefono",
  "profilescreen.carrieremail": "Correo electronico",
  "profilescreen.logininfoheader": "Mi Sesión",
  "profilescreen.username": "Nombre de usuario",
  "profilescreen.password": "Contraseña",
  "profilescreen.seeall": "Ver Todos",
  "editprofile.title": "Editar Perfil",
  "editprofile.save": "Guardar",
  "editprofile.cancel": "Cancelar",
  "profilescreen.edit": "Editar",
  "requestedtrip.title": "Viaje solicitado",
  "status.requested": "SOICITADO",
  "status.scheduled": "COORDINADO",
  "status.unassigned": "NO ASIGNADO",
  "status.enroute": "EN RUTA",
  "status.ontime": "A TIEMPO",
  "status.delayed": "ATRASADO",
  "status.approaching": "ACERCANDOSE",
  "status.loading": "CARGANDO",
  "status.arrived": "LLEGADO",
  "status.cancelled": "CANCELADO",
  "status.created": "CREADO",
  "status.on_schedule": "A TIEMPO",
  "status.processing": "PROCESANDO",
  "status.enroutetopickup": "EN RUTA HACIA CARGAR",
  "status.enroutetodestination": "EN RUTA HACIA DESTINO",
  "status.unloading": "DESCARGANDO",
  "status.completed": "COMPLETADO",
  "trip.pickup": "Recoger",
  "trip.complete": "COMPLETAR VIAJE",
  "trip.completed": "VIAJE COMPLETADO",
  "trip.closetrip": "CERRAR VIAJE",
  "trip.startunloading": "EMPEZAR DESCARGA",
  "trip.beginchecklist": "INICIAR LISTA DE VERIFICACION",
  "trip.delivery": "Entrega",
  "trip.reportarrival": "REPORTAR LLEGADA",
  "trip.leavefordes": "SALIR A DESTINO",
  "trip.estimateddistance": "Distancia Estimada",
  "trip.accept": "ACEPTAR",
  "trip.starttrip": "SALIR A CARGAR",
  "trip.loadtruck": "INICIAR LISTA DE VERIFICACIÓN",
  "trip.reject": "RECHAZO Y EXPLICACION",
  "trip.startloading": "COMENZAR A CARGAR",
  "trip.reportdelay": "REPORTAR TARDANZA",
  "trip.leaveforpickup": "SALIR A CARGAR",
  "trip.startprocessing": "COMENZAR LA CARGA",
  "trip.manifest": "MANIFIESTO",
  "trip.notes": "INSTRUCCIONES",
  "trip.qrcode": "Ver código QR",
  "trip.photos": "FOTOS",
  "trip.team": "Equipo",
  "trip.docs": "DOCUMENTOS",
  "trip.docs.bol": "GUÍA DE CARGA",
  "trip.docs.receipts": "RECIBOS",
  "trip.docs.others": "OTROS",
  "trip.docs.pod": "EVIDENCIA DE ENTREGA",
  "trip.photos.manifest": "IMAGENES DE MANIFIESTO",
  "trip.photos.truck": "FOTOS DE CAMION",
  "trip.photos.others": "OTROS",
  "trip.upcomingtrip": "Próximo Viaje",
  "trip.collaborators": "COLABORADES",
  "trip.docsuploadmessage":
    "Toque el icono de la camara para capturar fotos de documentos importantes",
  "trip.title.completed": "Viaje Completado",
  "trip.title.requested": "Viaje Solicitado",
  "trip.title.scheduled": "Viaje Coordinado",
  "trip.title.currenttrip": "Viaje Actual",
  "trip.title.loading": "Cargando...",
  "trip.title.error": "Detalle del Viaje",
  "manifest.liquidsolid": "Líquido/Sólido",
  "manifest.poundstogallons": "Libras a Galones",
  "manifest.packageno": "Numéro de Paquete",
  "manifest.plannedamount": "Cantidad Planificada",
  "manifest.loadedpounds": "Libras Cargadas",
  "manifest.unloadedpounds": "Libras Descargadas",
  "manifest.loadedgallons": "Galones Cargados",
  "manifest.unloadedgallons": "Galones Descargados",
  "manifest.description": "Descripción",
  "manifest.quantity": "Cantidad",
  "manifest.length": "Largo",
  "manifest.width": "Ancho",
  "manifest.height": "Altura",
  "manifest.weight": "Peso",
  "processshipment.title": "Procesar Viaje",
  "processshipment.pre_loading.title":
    "Usted ha completado la carga ¿Dejar para el destino?",
  "processshipment.post_loading.title":
    "Usted ha terminado la descargar ¿Completar y cerrar el envío?",
  "processshipment.yes": "Sí",
  "processshipment.no": "No",
  "process.finished": "TERMINADO",
  "stage.driver": "Etapa #1: Operador",
  "stage.qualifications": "Etapa #2: Calificaciones",
  "stage.loading": "Etapa 3: Carga",
  "qrcode.title": "Codigo Qr",
  "qr.message":
    "Muestre este código a la tripulación terrestre al llegar al destino",
  "qr.button": "LISTO",
  "rejection.title": "Viaje Solicitado",
  "rejection.delaytitle": "",
  "rejection.delay": "Viaje Actual",
  "rejection.reportdelay": "REPORTAR TARDANZA",
  "rejection.thanks": "¡Gracias!",
  "rejection.message": "Indique la razon por rechazo",
  "rejection.delaymessage": "Por favor indique la razon por la demora",
  "rejection.button": "LISTO",
  "rejection.placeholder": "Escriba aqui",
  "tabs.current": "Actual",
  "tabs.scheduled": "Coordinado",
  "tabs.requested": "Solicitado",
  "tabs.completed": "Completado",
  "tabs.shipments": "Envios",
  "messages.title": "Notificaciones",
  "messages.header.new": "NUEVO",
  "messages.header.earlier": "MÁS TEMPRANO",
  "chat.viewcontacts": "Ver Equipo",
  "notification.driver": "Operador",
  "chat.goto": "Ir",
  "chatcontacts.title": "Contactos",
  "chatrole.lm": "Gerente de Logística",
  "trip.contacts": "Mensajes",
  "trip.showmorephotos": "Mostrar Más Fotos",
  "error.required": "Campo Requerido",
  "error.valid.email": "Correo electronico no valido",
  "error.validnumber": "Debe ser un numero valido",
  "error.mustbephone": "Debe ser un telefono valido",
  "error.phone.required": "Telefono es requerido",
  "error.username.required": "Telefono es requerido",
  "error.password.minlength": "Minimo 6 caracteres",
  "error.password.required": "Contraseña requerida",
  "error.notripsavailable": "No hay viajes disponibles",
  "error.signin.otp.minlength": "Debe ser 6 caracteres",
  "error.signin.otp.requried": "Codigo de verificacion es requerido",
  "error.nonotification": "Sin notificaciones por el momento",
  "error.signup.firstname": "Nombre no valido",
  "error.signup.driver.licence": "Licencia no valida, ejemplo (us 29292)",
  "error.signup.truck.licence": "Formato de placa no valido (us233)",
  "error.signup.driver.licence.length":
    "Demaciado grande, intente uno mas corto",
  "error.signup.email": "Correo electronico no valido",
  "error.signup.email.required": "Correo electronico requerido",
  "error.retry": "INTENTAR DE NUEVO",
  "error.rejection.empty": "Elija una razon",
  "contacts.owner": "Dueño",
  "contacts.driver": "Operador",
  "contacts.follower": "Seguidor",
  "contacts.carrier-contact": "Portador",
  "contacts.consignee-contact": "Consignatario",
  "contacts.consignee-ground": "Consignatario",
  "contacts.shipper-contact": "Expeditor",
  "contacts.logisticsmanager": "Gerente de Logistica",
  "contacts.shipper-ground": "Expeditor",
  "imagepicker.title": "Escoger Imagen de",
  "imagepicker.gallery": "Galeria",
  "imagepicker.camera": "Camara",
  "imagepicker.loading": "Por favor espere...",
  "modal.warning.title": "Estas seguro?",
  "modal.warning.confirm": "Confrimar",
  "modal.warning.cancel": "Cancelar",
  "profile.edit.save": "Guardar",
  "profile.edit.cancel": "Cancelar",
  "error.profileupdate.name.required": "Campo Requerido",
  "error.profileupdate.name.max": "Oops, el nombre es muy largo.",
  // new
  "profilescreen.swtichLang": "Change Language to english",
  "profilescreen.changelanguage": "Selección de idioma",
  "profilescreen.lastupdated": "Última actualización",
  "profilescreen.lang.en": "English",
  "profilescreen.lang.es": "Español",
  "codepush.title": "Hay disponible una actualización",
  "codepush.optionalupdatemessage":
    "Hay disponible una actualización. ¿Te gustaría instalarlo?",
  "codepush.mandatoryupdatemessage":
    "Hay una actualización disponible que debe instalarse.",
  "codepush.installbuttonlabel": "Instalar en pc",
  "codepush.optionalignorebuttonlabel": "Ignorar",
  "codepush.mandatorycontinuebutton": "Seguir"
};
